version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: '${DB_CONNECTION}'
            DB_HOST: '${DB_HOST}'
            DB_PORT: '${DB_PORT}'
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'

    webserver:
        image: nginx:alpine
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - app

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
